import React, { useState } from 'react';
import { ProjectState } from '../../types';
import { EvidenceBadge } from '../EvidenceBadge';
import {
  TrendingUp,
  Calendar,
  Layers,
  ArrowUpRight,
  ArrowDownRight,
  ShieldCheck,
  RotateCcw,
  Sparkles,
  GitCompare,
  Clock,
} from 'lucide-react';

interface ChangesOverTimeViewProps {
  project: ProjectState;
}

export const ChangesOverTimeView: React.FC<ChangesOverTimeViewProps> = ({ project }) => {
  const [baselineDate, setBaselineDate] = useState('2026-08-20');
  const [compareDate, setCompareDate] = useState('2026-08-21');

  // Diagnostic timeline events
  const timelineEvents = [
    {
      date: '2026-08-21 09:25',
      type: 'Live Diagnostic Run',
      platform: 'Gemini 3.6 Flash',
      change: `Observed ${project.targetDomain || 'target-domain'} citation in direct-intent head-to-head prompt cluster.`,
      impact: '+12% citation frequency',
      status: 'positive',
    },
    {
      date: '2026-08-21 09:18',
      type: 'Query Fan-out Shift',
      platform: 'OpenAI GPT-4o',
      change: 'Model search fan-out expanded from 2 to 4 queries, prioritizing local guide reviews.',
      impact: 'Added query: "licensed private guide vs agency"',
      status: 'neutral',
    },
    {
      date: '2026-08-20 16:40',
      type: 'Competitor Citation Rise',
      platform: 'Claude 3.7 Sonnet',
      change: 'LivItaly cited for art-historian credential tags on Vatican queries.',
      impact: 'Competitor citation frequency +20%',
      status: 'negative',
    },
    {
      date: '2026-08-20 10:00',
      type: 'Baseline Project Initialized',
      platform: 'Cross-platform',
      change: 'Initial 15 test runs completed across 3 models.',
      impact: 'Baseline target domain citation: 40%',
      status: 'neutral',
    },
  ];

  return (
    <div className="space-y-6">
      {/* Header Info */}
      <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <div>
          <div className="flex items-center gap-2">
            <TrendingUp className="w-5 h-5 text-indigo-600" />
            <h2 className="text-base font-bold text-slate-900">
              Changes Over Time & Citation Volatility Tracking
            </h2>
          </div>
          <p className="text-xs text-slate-500 mt-0.5">
            Monitor model prompt drift, newly extracted search queries, and citation stability deltas.
          </p>
        </div>

        <div className="flex items-center gap-2 text-xs">
          <EvidenceBadge label="Cross-run Pattern" size="sm" />
        </div>
      </div>

      {/* Metric comparison cards */}
      <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
        <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-xs">
          <span className="text-[10px] uppercase font-semibold text-slate-400 block tracking-wider">
            Target Domain Stability
          </span>
          <div className="flex items-baseline gap-2 mt-2">
            <span className="text-2xl font-bold text-slate-900">78.5%</span>
            <span className="text-xs font-semibold text-emerald-600 flex items-center">
              <ArrowUpRight className="w-3.5 h-3.5" /> +4.2%
            </span>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Consistency of target page citation across repeated runs of identical prompt seeds.
          </p>
        </div>

        <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-xs">
          <span className="text-[10px] uppercase font-semibold text-slate-400 block tracking-wider">
            Query Drift Volatility
          </span>
          <div className="flex items-baseline gap-2 mt-2">
            <span className="text-2xl font-bold text-slate-900">Low (0.18)</span>
            <span className="text-xs font-semibold text-slate-500">Stable</span>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Variability in search queries generated by AI search tools when repeating prompts.
          </p>
        </div>

        <div className="bg-white rounded-xl border border-slate-200 p-4 shadow-xs">
          <span className="text-[10px] uppercase font-semibold text-slate-400 block tracking-wider">
            Active Experiments in Tracking
          </span>
          <div className="flex items-baseline gap-2 mt-2">
            <span className="text-2xl font-bold text-indigo-600">
              {project.experiments?.length || 2}
            </span>
            <span className="text-xs text-slate-500">Targeting 2 pages</span>
          </div>
          <p className="text-xs text-slate-500 mt-1">
            Scheduled re-tests to measure whether content updates improved citation likelihood.
          </p>
        </div>
      </div>

      {/* Timeline Audit Log */}
      <div className="bg-white rounded-xl border border-slate-200 p-5 shadow-xs">
        <h3 className="text-sm font-bold text-slate-900 mb-4 flex items-center gap-2">
          <Clock className="w-4 h-4 text-indigo-600" />
          Observable Diagnostic Timeline
        </h3>

        <div className="space-y-4">
          {timelineEvents.map((evt, idx) => (
            <div
              key={idx}
              className="flex items-start gap-3.5 pb-4 border-b border-slate-100 last:border-0 last:pb-0"
            >
              <div
                className={`w-8 h-8 rounded-full flex items-center justify-center flex-shrink-0 text-xs font-bold ${
                  evt.status === 'positive'
                    ? 'bg-emerald-100 text-emerald-700'
                    : evt.status === 'negative'
                    ? 'bg-rose-100 text-rose-700'
                    : 'bg-slate-100 text-slate-700'
                }`}
              >
                {evt.status === 'positive' ? '✓' : evt.status === 'negative' ? '!' : '•'}
              </div>

              <div className="flex-1 text-xs">
                <div className="flex items-center justify-between gap-2 flex-wrap mb-1">
                  <div className="flex items-center gap-2">
                    <span className="font-bold text-slate-900">{evt.type}</span>
                    <span className="text-[10px] bg-slate-100 text-slate-600 px-2 py-0.5 rounded font-mono">
                      {evt.platform}
                    </span>
                  </div>
                  <span className="text-slate-400 font-mono text-[11px]">{evt.date}</span>
                </div>

                <p className="text-slate-700 leading-relaxed">{evt.change}</p>
                <div className="mt-1 font-medium text-[11px] text-indigo-600">{evt.impact}</div>
              </div>
            </div>
          ))}
        </div>
      </div>
    </div>
  );
};
